apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chart-verifier
  annotations:
    github.com/project-slug: lokanandaprabhu/chart-verifier
spec:
  type: other
  lifecycle: unknown
  owner: user:development/guest
